### ISSUE TITLE
Technology lists

### ISSUE THREAD

**Issue by pjohnmeyer** [Pocolius/liftoff-assignments#2]
We need to work together to firm up your technology lists. Yes, they can change, but there's not a lot of time for changes in an 8 week project.

Spending time on developing your user stories might help us pin this down tomorrow.

**Comment by Pocolius** [comment]
At this time, I don't know of any other technologies I plan on using. I've updated the .md file accordingly.

**Comment by pjohnmeyer** [comment]
Looks good now, thanks.
