### ISSUE TITLE
C1: GitHub / LinkedIn Profile feedback

### ISSUE THREAD

**Issue by pjohnmeyer** [Pocolius/liftoff-assignments#3]
I really like your LinkedIn summary; it is precisely what I would like to see. (Also, super cool that you work at Miniature Market, that place is dope.)

A few notes:

* It would be nice to see a profile pic and/or bio on your GitHub profile as well. There's nothing wrong with just having a cool image as your profile pic, though.
* Your LinkedIn profile should include your LinkedIn education and highlighted technical skills, unless you prefer to leave those off for some reason?
* There are several disconnects between your resume and your LinkedIn profile; the only work experience you have on LinkedIn is not on your resume. None of your education appears on your LinkedIn profile. Consider what you want to include and what you want to exclude, but make sure the things that are in both places at least overlap.
* Consider pinning the repos you want to highlight on GitHub, otherwise GitHub decides which "popular" repositories to display on your profile.

**Comment by Pocolius** [comment]
I've corrected the issues as you noted them. I went ahead and made a technical resume and updated it to the Repo. My LinkedIn profile now matches said resume. I've also pinned a couple of repos on Github so they are highlighted over others. If you could look over things and let me know if you have any other thoughts in regards to them, I would appreciate it.

**Comment by pjohnmeyer** [comment]
Looks great, thanks!
